version: '1.0.0'

services:
  postgres:
    image: postgres
    restart: 'always'
    environment:
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: '1234'
    ports:
      - 5432:5432
  web:
    build: ./
    command: uvicorn main:app --host=0.0.0.0 --reload
    volumes:
      - .:/usr/src/cnw
    ports:
      - 8000:8000
    depends_on:
      - postgres
  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart:
      always
    environment:
      ADMINER_DESIGN: 'hydra'
